// =====================================================================
// Candidate Matching Profile & Search Rules Configuration
// =====================================================================

const candidateProfile = {
  name: "Candidate",
  title: "Early-Career Software Engineer / Java Full Stack Developer",
  experienceMonths: 10, // ~8-12 months professional software development experience
  experienceYearsRange: "0-2 years",
  education: {
    degree: "B.Tech in Computer Science and Engineering",
    graduationYear: 2025,
    eligibleForFresherRoles: true
  },
  primarySkills: [
    "Java",
    "Core Java",
    "Java 17",
    "Spring Boot",
    "Spring MVC",
    "REST APIs",
    "JDBC",
    "JPA",
    "Hibernate",
    "Maven",
    "MySQL",
    "SQL",
    "React.js",
    "JavaScript",
    "HTML",
    "CSS",
    "Git",
    "GitHub",
    "SDLC",
    "Agile",
    "Scrum",
    "Debugging",
    "Backend Development",
    "Full Stack Development"
  ],
  secondarySkills: [
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "AWS",
    "Docker",
    "CI/CD",
    "TypeScript",
    "Tailwind CSS",
    "Bootstrap"
  ],
  achievements: [
    "Developed 15+ RESTful APIs using Java and Spring Boot",
    "Worked on Java/Spring Boot backend microservices and data persistence",
    "Optimized relational MySQL queries and schema designs",
    "Integrated dynamic React.js frontend interfaces with backend REST endpoints",
    "Implemented Git branching workflows in Agile sprint teams"
  ],
  targetRoles: [
    "Software Engineer",
    "Software Developer",
    "Associate Software Engineer",
    "Associate Software Developer",
    "Junior Software Engineer",
    "Junior Software Developer",
    "Java Developer",
    "Junior Java Developer",
    "Java Software Engineer",
    "Java Backend Developer",
    "Backend Developer",
    "Backend Engineer",
    "Spring Boot Developer",
    "Java Spring Boot Developer",
    "Full Stack Developer",
    "Java Full Stack Developer",
    "Full Stack Engineer",
    "Application Developer",
    "Application Engineer",
    "Graduate Engineer Trainee",
    "Graduate Software Engineer",
    "Trainee Software Engineer",
    "Trainee Developer",
    "Technology Analyst - Entry Level",
    "Programmer Analyst - Entry Level",
    "Associate Engineer",
    "Software Engineer I",
    "Developer I",
    "SDE I",
    "Entry-Level Software Developer"
  ],
  targetLocations: [
    "Hyderabad",
    "Bengaluru",
    "Bangalore",
    "Chennai",
    "Pune",
    "Mumbai",
    "Remote",
    "Remote India",
    "PAN India",
    "Noida",
    "Gurugram",
    "Gurgaon",
    "Delhi NCR",
    "Kochi",
    "Coimbatore",
    "Ahmedabad"
  ],
  scoringWeights: {
    technicalSkills: 0.35,
    experienceEligibility: 0.20,
    roleMatch: 0.15,
    freshness: 0.15,
    locationMatch: 0.10,
    educationEligibility: 0.05
  },
  skillPoints: {
    "java": 10,
    "spring boot": 10,
    "rest api": 5,
    "backend": 5,
    "react": 5,
    "mysql": 5,
    "sql": 5,
    "jpa": 3,
    "hibernate": 3,
    "microservices": 3,
    "git": 2,
    "aws": 2,
    "docker": 2,
    "maven": 2,
    "javascript": 2
  },
  searchQueries: [
    "Java Developer fresher India",
    "Spring Boot Developer 0-2 years India",
    "Software Engineer fresher India",
    "Associate Software Engineer India",
    "Java Backend Developer junior India",
    "Backend Developer Java Spring Boot Hyderabad",
    "Java Developer Bangalore 0-2 years",
    "Full Stack Developer Java React India",
    "Software Engineer React Spring Boot India",
    "Graduate Software Engineer India",
    "Trainee Software Engineer India",
    "Software Developer 2025 graduate India",
    "Associate Engineer Java India",
    "SDE 1 Java India",
    "Software Engineer I India",
    "Junior Java Developer India",
    "Java Spring Boot React Hyderabad",
    "Java Developer Pune 0-1 years",
    "Associate Software Developer Chennai",
    "Java Full Stack Developer Remote India"
  ]
};

module.exports = candidateProfile;
